name: show_pictures
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0  
  flutter_bloc: ^8.1.1
  dio: ^5.3.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  sqflite: ^2.1.0+1
  conditional_builder_null_safety: ^0.0.6
  cached_network_image: ^3.2.2
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.2
  injectable: ^2.3.0
  logger: ^2.0.2
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.3
  flutter_screenutil: ^5.9.0
  go_router: ^10.1.2
  flutter_svg: ^2.0.7
  text_scroll: ^0.2.0
  auto_size_text: ^3.0.0
  flutter_form_builder: ^9.1.0
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3



  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
